/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c69ba44d-01cf-4c2a-b8b0-4d3139565096",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MYlXAHyzZ",
    "aws_user_pools_web_client_id": "2maolvjtnsntk8srlv7fb6p65d",
    "oauth": {},
    "aws_user_files_s3_bucket": "monkfish68c6aa149d6643fa8ec875b634129e3914450-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
